XQMprViewer: ui::ControllerPanelCornerAnnotationItem Class Reference
ui::ControllerPanelCornerAnnotationItem Class Reference
Control panel item for corner annotation overlay configuration.
#include <ControllerPanelCornerAnnotationItem.hpp>
Public Member Functions
ControllerPanelCornerAnnotationItem (QWidget *parent=nullptr)
~ControllerPanelCornerAnnotationItem () override
void AddOverlay (overlays::CornerAnnotationOverlay *overlay)
void ClearOverlays ()
signals::void CornerAnnotationEnableChanged (bool enabled)
void CornerAnnotationPositionChanged (const overlays::OverlayPosition &position)
void CornerAnnotationColorChanged (const QColor &color)
void CornerAnnotationFontSizeChanged (int fontSize)
void CornerAnnotationMarginChanged (int margin)
void CornerAnnotationShowSliceInfoChanged (bool show)
void CornerAnnotationShowWindowLevelChanged (bool show)
void CornerAnnotationShowSpacingChanged (bool show)
void CornerAnnotationShowViewNameChanged (bool show)
Detailed Description
Control panel item for corner annotation overlay configuration.
Manages one or more CornerAnnotationOverlay instances simultaneously. All attached overlays are kept in sync with the panel settings.
Controls:
Enable / disable (checkbox)
Position (combo: same options as FPS overlay)
Show slice info (checkbox)
Show window/level (checkbox)
Show spacing (checkbox)
Show view name (checkbox)
Font size (spin box, pt)
Margin (spin box, px)
Text color (color picker button)
Definition at line 34 of file ControllerPanelCornerAnnotationItem.hpp.
Constructor & Destructor Documentation
ControllerPanelCornerAnnotationItem()
ui::ControllerPanelCornerAnnotationItem::ControllerPanelCornerAnnotationItem (QWidget * parent = nullptr) explicit
Definition at line 16 of file ControllerPanelCornerAnnotationItem.cpp.
~ControllerPanelCornerAnnotationItem()
ui::ControllerPanelCornerAnnotationItem::~ControllerPanelCornerAnnotationItem () override default
Member Function Documentation
AddOverlay()
void ui::ControllerPanelCornerAnnotationItem::AddOverlay (overlays::CornerAnnotationOverlay * overlay)
Definition at line 23 of file ControllerPanelCornerAnnotationItem.cpp.
References overlays::CornerAnnotationOverlay::SetEnabled(), overlays::CornerAnnotationOverlay::SetFontSize(), overlays::CornerAnnotationOverlay::SetMargin(), overlays::CornerAnnotationOverlay::SetPosition(), overlays::CornerAnnotationOverlay::SetShowSliceInfo(), overlays::CornerAnnotationOverlay::SetShowSpacing(), overlays::CornerAnnotationOverlay::SetShowViewName(), overlays::CornerAnnotationOverlay::SetShowWindowLevel(), and overlays::CornerAnnotationOverlay::SetTextColor().
ClearOverlays()
void ui::ControllerPanelCornerAnnotationItem::ClearOverlays ()
Definition at line 38 of file ControllerPanelCornerAnnotationItem.cpp.
CornerAnnotationColorChanged()
void ui::ControllerPanelCornerAnnotationItem::CornerAnnotationColorChanged (const QColor & color)
CornerAnnotationEnableChanged()
signals::void ui::ControllerPanelCornerAnnotationItem::CornerAnnotationEnableChanged (bool enabled)
CornerAnnotationFontSizeChanged()
void ui::ControllerPanelCornerAnnotationItem::CornerAnnotationFontSizeChanged (int fontSize)
CornerAnnotationMarginChanged()
void ui::ControllerPanelCornerAnnotationItem::CornerAnnotationMarginChanged (int margin)
CornerAnnotationPositionChanged()
void ui::ControllerPanelCornerAnnotationItem::CornerAnnotationPositionChanged (const overlays::OverlayPosition & position)
CornerAnnotationShowSliceInfoChanged()
void ui::ControllerPanelCornerAnnotationItem::CornerAnnotationShowSliceInfoChanged (bool show)
CornerAnnotationShowSpacingChanged()
void ui::ControllerPanelCornerAnnotationItem::CornerAnnotationShowSpacingChanged (bool show)
CornerAnnotationShowViewNameChanged()
void ui::ControllerPanelCornerAnnotationItem::CornerAnnotationShowViewNameChanged (bool show)
CornerAnnotationShowWindowLevelChanged()
void ui::ControllerPanelCornerAnnotationItem::CornerAnnotationShowWindowLevelChanged (bool show)
The documentation for this class was generated from the following files:
src/ui/include/ui/ControllerPanelCornerAnnotationItem.hpp
src/ui/src/ControllerPanelCornerAnnotationItem.cpp