XQMprViewer: controllers::SliceController Class Reference
controllers::SliceController Class Reference
Manages up to three vtkResliceImageViewer instances for orthogonal slice display.
#include <SliceController.hpp>
Public Types
enum Orientation { Axial = 0 , Coronal = 1 , Sagittal = 2 }
using Vec3 = std::array< double, 3 >
Public Member Functions
SliceController (QObject *parent=nullptr)
~SliceController () override
void Initialize (const std::vector< QVTKOpenGLNativeWidget * > &vtkWidgets, render::RenderScheduler *scheduler)
Initialises the viewers from the provided widget list.
void SetImageData (vtkImageData *image)
Pushes image into the reslice pipeline and requests a render.
void GetRenderers (std::vector< vtkSmartPointer< vtkRenderer > > &outRenderers) const
Fills outRenderers with the renderer from each viewer.
void RequestRenderAll ()
Request a render for all registered RIV windows via the scheduler.
void RenderAll ()
Convenience: RequestRenderAll() + Flush() in one call.
const std::vector< vtkSmartPointer< vtkResliceImageViewer > > & GetViewers () const
Returns the underlying viewer list, e.g. for use by ViewportInteractorStyle.
render::RenderScheduler * Scheduler () const
Exposes the scheduler so parent controllers can call Flush().
void FitToView ()
Fit each plane's camera to fill its viewport exactly.
Public Member Functions inherited from controllers::IControllerBase
IControllerBase (QObject *parent=nullptr)
~IControllerBase () override=default
Public Attributes
: void OnSphereUpdated(const Vec3& worldPos)
Public Attributes inherited from controllers::IControllerBase
: void StatusChanged(const QString& message)
Detailed Description
Manages up to three vtkResliceImageViewer instances for orthogonal slice display.
Supports two operating modes, detected automatically from the widget vector size:
3 widgets → multi-window mode: each viewer owns a separate render window.
1 widget → viewport mode: all viewers share one render window; interaction routing is handled externally by ViewportInteractorStyle.
Definition at line 32 of file SliceController.hpp.
Member Typedef Documentation
Vec3
using controllers::SliceController::Vec3 = std::array<double, 3>
Definition at line 41 of file SliceController.hpp.
Member Enumeration Documentation
Orientation
enum controllers::SliceController::Orientation
Enumerator
Axial
Coronal
Sagittal
Definition at line 36 of file SliceController.hpp.
Constructor & Destructor Documentation
SliceController()
controllers::SliceController::SliceController (QObject * parent = nullptr) explicit
Definition at line 24 of file SliceController.cpp.
~SliceController()
controllers::SliceController::~SliceController () override default
Member Function Documentation
FitToView()
void controllers::SliceController::FitToView ()
Fit each plane's camera to fill its viewport exactly.
Safe to call at any time; no-ops if image data is not yet loaded. Call after viewport geometry changes (layout switch) to avoid letterboxing.
Definition at line 179 of file SliceController.cpp.
GetRenderers()
void controllers::SliceController::GetRenderers (std::vector< vtkSmartPointer< vtkRenderer > > & outRenderers) const
Fills outRenderers with the renderer from each viewer.
Definition at line 120 of file SliceController.cpp.
GetViewers()
const std::vector< vtkSmartPointer< vtkResliceImageViewer > > & controllers::SliceController::GetViewers () const
Returns the underlying viewer list, e.g. for use by ViewportInteractorStyle.
Definition at line 288 of file SliceController.cpp.
Initialize()
void controllers::SliceController::Initialize (const std::vector< QVTKOpenGLNativeWidget * > & vtkWidgets, render::RenderScheduler * scheduler)
Initialises the viewers from the provided widget list.
Pass 3 widgets for multi-window mode or 1 widget for viewport mode.
Parameters
scheduler Render scheduler owned by the parent IViewController. SliceController registers its RIV targets here and uses RequestRender/Flush for all rendering.
Definition at line 29 of file SliceController.cpp.
RenderAll()
void controllers::SliceController::RenderAll ()
Convenience: RequestRenderAll() + Flush() in one call.
Definition at line 277 of file SliceController.cpp.
References render::RenderScheduler::Flush(), and RequestRenderAll().
RequestRenderAll()
void controllers::SliceController::RequestRenderAll ()
Request a render for all registered RIV windows via the scheduler.
Callers should follow this with Scheduler()->Flush() (or the parent controller's Flush path) when all state mutations for the current event are complete.
Definition at line 268 of file SliceController.cpp.
References render::RenderScheduler::RequestRender().
Referenced by RenderAll(), and SetImageData().
Scheduler()
render::RenderScheduler * controllers::SliceController::Scheduler () const
Exposes the scheduler so parent controllers can call Flush().
Definition at line 283 of file SliceController.cpp.
SetImageData()
void controllers::SliceController::SetImageData (vtkImageData * image)
Pushes image into the reslice pipeline and requests a render.
Definition at line 108 of file SliceController.cpp.
References RequestRenderAll().
Member Data Documentation
__pad0__
controllers::SliceController::__pad0__
Definition at line 87 of file SliceController.hpp.
The documentation for this class was generated from the following files:
src/controllers/include/controllers/SliceController.hpp
src/controllers/src/SliceController.cpp