XQMprViewer: ui::ViewportLayoutManager Class Reference
ui::ViewportLayoutManager Class Reference
Global orchestrator for runtime layout switching.
#include <ViewportLayoutManager.hpp>
Public Member Functions
ViewportLayoutManager (QObject *parent=nullptr)
~ViewportLayoutManager () override
void RegisterTarget (ILayoutTarget *target)
Register a view as a layout target.
void RegisterOverlayAdapter (std::unique_ptr< adapters::OverlayLayoutAdapter > adapter)
Register an overlay adapter that will be synced on every layout change.
void SetOrientationMarkersEnabled (bool enabled)
Forward the global orientation-marker user-enable state to all adapters.
void SetCornerAnnotationsEnabled (bool enabled)
Forward the global corner-annotation user-enable state to all adapters.
const ViewportLayoutDefinition & CurrentLayout () const
void ApplySlotAssignment (const std::vector< int > &slotPlanes)
Re-apply current layout with a custom slot→plane assignment.
signals::void layoutChanged (const ui::ViewportLayoutDefinition &def)
Public Attributes
: void ApplyLayout(ui::ViewportLayoutType type)
Detailed Description
Global orchestrator for runtime layout switching.
Owned by MainWindow. Drives layout changes across both views:
Calls ILayoutTarget::ApplyLayout() on every registered view.
Calls OverlayLayoutAdapter::Sync() on every registered adapter.
Keeps the current layout definition so new views can query it.
Decouples the selector widget (ViewportLayoutSelector / ViewportLayoutPanel) from both the view layer and the controller layer.
Overlay enable/disable events from the ControllerPanel must also pass through this manager so it can forward them to the correct adapters.
Definition at line 30 of file ViewportLayoutManager.hpp.
Constructor & Destructor Documentation
ViewportLayoutManager()
ui::ViewportLayoutManager::ViewportLayoutManager (QObject * parent = nullptr) explicit
Definition at line 7 of file ViewportLayoutManager.cpp.
~ViewportLayoutManager()
ui::ViewportLayoutManager::~ViewportLayoutManager () override default
Member Function Documentation
ApplySlotAssignment()
void ui::ViewportLayoutManager::ApplySlotAssignment (const std::vector< int > & slotPlanes)
Re-apply current layout with a custom slot→plane assignment.
slotPlanes[i] = plane index (0=Axial,1=Coronal,2=Sagittal) for slot i. The geometry (viewport rects) stay the same; only which plane renders in each slot changes.
Definition at line 33 of file ViewportLayoutManager.cpp.
References layoutChanged(), ui::MakeLayoutDefinition(), and ui::ViewportLayoutDefinition::type.
CurrentLayout()
const ViewportLayoutDefinition & ui::ViewportLayoutManager::CurrentLayout () const inline
Definition at line 74 of file ViewportLayoutManager.hpp.
layoutChanged()
signals::void ui::ViewportLayoutManager::layoutChanged (const ui::ViewportLayoutDefinition & def)
Referenced by ApplySlotAssignment().
RegisterOverlayAdapter()
void ui::ViewportLayoutManager::RegisterOverlayAdapter (std::unique_ptr< adapters::OverlayLayoutAdapter > adapter)
Register an overlay adapter that will be synced on every layout change.
Ownership is transferred to the manager.
Definition at line 20 of file ViewportLayoutManager.cpp.
RegisterTarget()
void ui::ViewportLayoutManager::RegisterTarget (ILayoutTarget * target)
Register a view as a layout target.
The caller retains ownership. ApplyLayout() is called immediately with the current layout when a new target registers.
Definition at line 12 of file ViewportLayoutManager.cpp.
References ui::ILayoutTarget::ApplyLayout().
SetCornerAnnotationsEnabled()
void ui::ViewportLayoutManager::SetCornerAnnotationsEnabled (bool enabled)
Forward the global corner-annotation user-enable state to all adapters.
Called by MainWindow when ControllerPanel emits CornerAnnotationEnableChanged.
Definition at line 44 of file ViewportLayoutManager.cpp.
SetOrientationMarkersEnabled()
void ui::ViewportLayoutManager::SetOrientationMarkersEnabled (bool enabled)
Forward the global orientation-marker user-enable state to all adapters.
Called by MainWindow when ControllerPanel emits OrientationMarkerEnableChanged.
Definition at line 39 of file ViewportLayoutManager.cpp.
Member Data Documentation
__pad0__
ui::ViewportLayoutManager::__pad0__
Definition at line 74 of file ViewportLayoutManager.hpp.
The documentation for this class was generated from the following files:
src/ui/include/ui/ViewportLayoutManager.hpp
src/ui/src/ViewportLayoutManager.cpp