XQMprViewer: controllers::DicomController Class Reference
controllers::DicomController Class Reference
Scans a directory for DICOM series and loads them asynchronously.
#include <DicomController.hpp>
Classes
struct SeriesInfo
Metadata for a single DICOM series found during a directory scan.
Public Member Functions
DicomController (QObject *parent=nullptr)
~DicomController () override
void LoadDicom (const std::string &directory)
Starts an asynchronous scan of directory for DICOM series. Emits SeriesListReady when complete.
void LoadSeries (int seriesIndex)
Loads the series at seriesIndex from the last scanned directory. Emits ImageDataReady when the image is ready.
const std::vector< SeriesInfo > & GetSeries () const
Returns the series list populated by the last LoadDicom() call.
vtkDICOMReader * GetReader () const
Returns the underlying VTK reader after a series has been loaded, nullptr otherwise.
void ImageDataReady (vtkImageData *imageData)
Emitted after a series has been loaded.
Public Member Functions inherited from controllers::IControllerBase
IControllerBase (QObject *parent=nullptr)
~IControllerBase () override=default
Public Attributes
: void SeriesListReady(int seriesCount)
Public Attributes inherited from controllers::IControllerBase
: void StatusChanged(const QString& message)
Detailed Description
Scans a directory for DICOM series and loads them asynchronously.
Call LoadDicom() to start a background scan; connect SeriesListReady to learn the number of series found. Call LoadSeries() to read a specific series and connect ImageDataReady to receive the resulting vtkImageData.
Definition at line 29 of file DicomController.hpp.
Constructor & Destructor Documentation
DicomController()
controllers::DicomController::DicomController (QObject * parent = nullptr) explicit
Definition at line 20 of file DicomController.cpp.
~DicomController()
controllers::DicomController::~DicomController () override
Definition at line 29 of file DicomController.cpp.
Member Function Documentation
GetReader()
vtkDICOMReader * controllers::DicomController::GetReader () const
Returns the underlying VTK reader after a series has been loaded, nullptr otherwise.
Definition at line 78 of file DicomController.cpp.
GetSeries()
const std::vector< DicomController::SeriesInfo > & controllers::DicomController::GetSeries () const
Returns the series list populated by the last LoadDicom() call.
Definition at line 74 of file DicomController.cpp.
ImageDataReady()
void controllers::DicomController::ImageDataReady (vtkImageData * imageData)
Emitted after a series has been loaded.
Parameters
imageData The loaded image.
References LoadSeries().
Referenced by adapters::DicomMetaDataAdapter::DicomMetaDataAdapter().
LoadDicom()
void controllers::DicomController::LoadDicom (const std::string & directory)
Starts an asynchronous scan of directory for DICOM series. Emits SeriesListReady when complete.
Definition at line 37 of file DicomController.cpp.
LoadSeries()
void controllers::DicomController::LoadSeries (int seriesIndex)
Loads the series at seriesIndex from the last scanned directory. Emits ImageDataReady when the image is ready.
Definition at line 54 of file DicomController.cpp.
Referenced by ImageDataReady().
Member Data Documentation
__pad0__
controllers::DicomController::__pad0__
Definition at line 62 of file DicomController.hpp.
The documentation for this class was generated from the following files:
src/controllers/include/controllers/DicomController.hpp
src/controllers/src/DicomController.cpp