XQMprViewer: qvv::ViewportManager::Impl Class Reference
qvv::ViewportManager::Impl Class Reference
Public Member Functions
void EnsureRenderWindow ()
void AttachTimingCallbacks ()
detail::ViewportSlot * FindSlot (int index)
const detail::ViewportSlot * FindSlot (int index) const
void ApplyViewportToRenderer (const detail::ViewportSlot &slot)
void NotifyFrameRendered (int index, const RenderStats &stats)
Static Public Member Functions
static void OnRenderStart (vtkObject *, unsigned long, void *clientData, void *)
static void OnRenderEnd (vtkObject *, unsigned long, void *clientData, void *)
Public Attributes
vtkSmartPointer< vtkRenderWindow > m_renderWindow
bool m_ownsWindow {false}
bool m_statsOverlayEnabled {false}
int m_nextIndex {0}
std::vector< detail::ViewportSlot > m_slots
std::vector< IViewportObserver * > m_observers
vtkSmartPointer< vtkCallbackCommand > m_startCallback
vtkSmartPointer< vtkCallbackCommand > m_endCallback
std::chrono::steady_clock::time_point m_renderStart
ViewportManager * m_owner {nullptr}
Detailed Description
Definition at line 34 of file ViewportManager.cpp.
Member Function Documentation
ApplyViewportToRenderer()
void qvv::ViewportManager::Impl::ApplyViewportToRenderer (const detail::ViewportSlot & slot) inline
Definition at line 93 of file ViewportManager.cpp.
References qvv::detail::ViewportSlot::config, and qvv::detail::ViewportSlot::renderer.
AttachTimingCallbacks()
void qvv::ViewportManager::Impl::AttachTimingCallbacks () inline
Definition at line 64 of file ViewportManager.cpp.
References m_endCallback, m_renderWindow, m_startCallback, OnRenderEnd(), and OnRenderStart().
Referenced by EnsureRenderWindow().
EnsureRenderWindow()
void qvv::ViewportManager::Impl::EnsureRenderWindow () inline
Definition at line 54 of file ViewportManager.cpp.
References AttachTimingCallbacks(), m_ownsWindow, and m_renderWindow.
FindSlot() [1/2]
detail::ViewportSlot * qvv::ViewportManager::Impl::FindSlot (int index) inline
Definition at line 79 of file ViewportManager.cpp.
References m_slots.
FindSlot() [2/2]
const detail::ViewportSlot * qvv::ViewportManager::Impl::FindSlot (int index) const inline
Definition at line 86 of file ViewportManager.cpp.
References m_slots.
NotifyFrameRendered()
void qvv::ViewportManager::Impl::NotifyFrameRendered (int index, const RenderStats & stats) inline
Definition at line 101 of file ViewportManager.cpp.
References qvv::RenderStats::frameTimeMs, m_observers, and m_owner.
OnRenderEnd()
static void qvv::ViewportManager::Impl::OnRenderEnd (vtkObject * , unsigned long , void * clientData, void *) inline static
Definition at line 113 of file ViewportManager.cpp.
Referenced by AttachTimingCallbacks().
OnRenderStart()
static void qvv::ViewportManager::Impl::OnRenderStart (vtkObject * , unsigned long , void * clientData, void *) inline static
Definition at line 108 of file ViewportManager.cpp.
References m_renderStart.
Referenced by AttachTimingCallbacks().
Member Data Documentation
m_endCallback
vtkSmartPointer<vtkCallbackCommand> qvv::ViewportManager::Impl::m_endCallback
Definition at line 46 of file ViewportManager.cpp.
Referenced by AttachTimingCallbacks().
m_nextIndex
int qvv::ViewportManager::Impl::m_nextIndex {0}
Definition at line 39 of file ViewportManager.cpp.
m_observers
std::vector<IViewportObserver*> qvv::ViewportManager::Impl::m_observers
Definition at line 42 of file ViewportManager.cpp.
Referenced by NotifyFrameRendered().
m_owner
ViewportManager* qvv::ViewportManager::Impl::m_owner {nullptr}
Definition at line 51 of file ViewportManager.cpp.
Referenced by NotifyFrameRendered().
m_ownsWindow
bool qvv::ViewportManager::Impl::m_ownsWindow {false}
Definition at line 37 of file ViewportManager.cpp.
Referenced by EnsureRenderWindow().
m_renderStart
std::chrono::steady_clock::time_point qvv::ViewportManager::Impl::m_renderStart
Definition at line 49 of file ViewportManager.cpp.
Referenced by OnRenderStart().
m_renderWindow
vtkSmartPointer<vtkRenderWindow> qvv::ViewportManager::Impl::m_renderWindow
Definition at line 36 of file ViewportManager.cpp.
Referenced by AttachTimingCallbacks(), and EnsureRenderWindow().
m_slots
std::vector<detail::ViewportSlot> qvv::ViewportManager::Impl::m_slots
Definition at line 41 of file ViewportManager.cpp.
Referenced by FindSlot(), and FindSlot().
m_startCallback
vtkSmartPointer<vtkCallbackCommand> qvv::ViewportManager::Impl::m_startCallback
Definition at line 45 of file ViewportManager.cpp.
Referenced by AttachTimingCallbacks().
m_statsOverlayEnabled
bool qvv::ViewportManager::Impl::m_statsOverlayEnabled {false}
Definition at line 38 of file ViewportManager.cpp.
The documentation for this class was generated from the following file:
lib/src/ViewportManager.cpp