XQMprViewer: ui::ControllerPanelFPSOverlayItem Class Reference
ui::ControllerPanelFPSOverlayItem Class Reference
Control panel item for FPS overlay configuration.
#include <ControllerPanelFPSOverlayItem.hpp>
Public Member Functions
ControllerPanelFPSOverlayItem (QWidget *parent=nullptr)
~ControllerPanelFPSOverlayItem () override
void AddOverlay (overlays::FPSOverlay *overlay)
Attach an overlay to be controlled by this panel.
void ClearOverlays ()
Detach all overlays.
signals::void FPSOverlayEnableChanged (bool enabled)
void FPSOverlayColorChanged (const QColor &color)
void FPSOverlayPositionChanged (const overlays::OverlayPosition &position)
void FPSOverlayMarginChanged (int margin)
void FPSOverlayFontSizeChanged (int fontSize)
void FPSOverlayAvgWindowChanged (int seconds)
Detailed Description
Control panel item for FPS overlay configuration.
Manages one or more FPSOverlay instances simultaneously. All attached overlays are kept in sync with the panel settings.
Controls:
Enable / disable toggle (checkbox)
Corner position (combo: Top-Left, Top-Right, Top-Center, Bottom-Left, Bottom-Right, Bottom-Center)
Margin (spin box, pixels)
Text color (color picker button)
Font size (spin box, pt)
Definition at line 33 of file ControllerPanelFPSOverlayItem.hpp.
Constructor & Destructor Documentation
ControllerPanelFPSOverlayItem()
ui::ControllerPanelFPSOverlayItem::ControllerPanelFPSOverlayItem (QWidget * parent = nullptr) explicit
Definition at line 16 of file ControllerPanelFPSOverlayItem.cpp.
~ControllerPanelFPSOverlayItem()
ui::ControllerPanelFPSOverlayItem::~ControllerPanelFPSOverlayItem () override default
Member Function Documentation
AddOverlay()
void ui::ControllerPanelFPSOverlayItem::AddOverlay (overlays::FPSOverlay * overlay)
Attach an overlay to be controlled by this panel.
Definition at line 23 of file ControllerPanelFPSOverlayItem.cpp.
References overlays::FPSOverlay::SetAveragingWindow(), overlays::FPSOverlay::SetEnabled(), overlays::FPSOverlay::SetFontSize(), overlays::FPSOverlay::SetMargin(), overlays::FPSOverlay::SetPosition(), and overlays::FPSOverlay::SetTextColor().
ClearOverlays()
void ui::ControllerPanelFPSOverlayItem::ClearOverlays ()
Detach all overlays.
Definition at line 36 of file ControllerPanelFPSOverlayItem.cpp.
FPSOverlayAvgWindowChanged()
void ui::ControllerPanelFPSOverlayItem::FPSOverlayAvgWindowChanged (int seconds)
FPSOverlayColorChanged()
void ui::ControllerPanelFPSOverlayItem::FPSOverlayColorChanged (const QColor & color)
FPSOverlayEnableChanged()
signals::void ui::ControllerPanelFPSOverlayItem::FPSOverlayEnableChanged (bool enabled)
FPSOverlayFontSizeChanged()
void ui::ControllerPanelFPSOverlayItem::FPSOverlayFontSizeChanged (int fontSize)
FPSOverlayMarginChanged()
void ui::ControllerPanelFPSOverlayItem::FPSOverlayMarginChanged (int margin)
FPSOverlayPositionChanged()
void ui::ControllerPanelFPSOverlayItem::FPSOverlayPositionChanged (const overlays::OverlayPosition & position)
The documentation for this class was generated from the following files:
src/ui/include/ui/ControllerPanelFPSOverlayItem.hpp
src/ui/src/ControllerPanelFPSOverlayItem.cpp