XQMprViewer: ui::ViewportLayoutSelector Class Reference
ui::ViewportLayoutSelector Class Reference
Toolbar-like panel that displays one ViewportLayoutItem per layout type.
#include <ViewportLayoutSelector.hpp>
Public Member Functions
ViewportLayoutSelector (QWidget *parent=nullptr)
void SetActiveLayout (ViewportLayoutType type)
Programmatically activates the button for type without emitting layoutSelected().
ViewportLayoutType ActiveLayout () const
Returns the currently checked layout type.
void UpdateActiveDefinition (const ViewportLayoutDefinition &def)
Update the definition of the active button (e.g. after slot reassignment).
void slotAssignmentRequested (const std::vector< int > &slotPlanes)
Emitted when the user picks a new slot→plane assignment via right-click on a layout button.
Public Attributes
: void layoutSelected(ui::ViewportLayoutType type)
Detailed Description
Toolbar-like panel that displays one ViewportLayoutItem per layout type.
Maintains an exclusive selection (QButtonGroup) and emits layoutSelected() whenever the active layout changes. The widget is pure UI — it knows nothing about renderers or controllers.
Embed it above or beside the VTK widget in ViewportView and connect its layoutSelected() signal to ViewportLayoutManager::ApplyLayout().
Definition at line 25 of file ViewportLayoutSelector.hpp.
Constructor & Destructor Documentation
ViewportLayoutSelector()
ui::ViewportLayoutSelector::ViewportLayoutSelector (QWidget * parent = nullptr) explicit
Definition at line 35 of file ViewportLayoutSelector.cpp.
References ui::HorizontalSplit, SetActiveLayout(), and slotAssignmentRequested().
Member Function Documentation
ActiveLayout()
ViewportLayoutType ui::ViewportLayoutSelector::ActiveLayout () const
Returns the currently checked layout type.
Definition at line 93 of file ViewportLayoutSelector.cpp.
References ui::HorizontalSplit.
SetActiveLayout()
void ui::ViewportLayoutSelector::SetActiveLayout (ViewportLayoutType type)
Programmatically activates the button for type without emitting layoutSelected().
Definition at line 86 of file ViewportLayoutSelector.cpp.
Referenced by ViewportLayoutSelector().
slotAssignmentRequested()
void ui::ViewportLayoutSelector::slotAssignmentRequested (const std::vector< int > & slotPlanes)
Emitted when the user picks a new slot→plane assignment via right-click on a layout button.
Referenced by ViewportLayoutSelector().
UpdateActiveDefinition()
void ui::ViewportLayoutSelector::UpdateActiveDefinition (const ViewportLayoutDefinition & def)
Update the definition of the active button (e.g. after slot reassignment).
Definition at line 101 of file ViewportLayoutSelector.cpp.
References ui::ViewportLayoutDefinition::type.
Member Data Documentation
__pad0__
ui::ViewportLayoutSelector::__pad0__
Definition at line 38 of file ViewportLayoutSelector.hpp.
The documentation for this class was generated from the following files:
src/ui/include/ui/ViewportLayoutSelector.hpp
src/ui/src/ViewportLayoutSelector.cpp