XQMprViewer: overlays::OrientationMarkerOverlay Class Reference
overlays::OrientationMarkerOverlay Class Reference
Anatomical orientation label overlay rendered as a child widget on top of a QVTKOpenGLNativeWidget.
#include <OrientationMarkerOverlay.hpp>
Public Types
enum class SliceOrientation { Axial = 0 , Coronal = 1 , Sagittal = 2 }
Public Member Functions
OrientationMarkerOverlay (QVTKOpenGLNativeWidget *host, SliceOrientation orientation=SliceOrientation::Axial)
~OrientationMarkerOverlay () override
void SetEnabled (bool enabled) override
Enable or disable the overlay.
void SetPosition (OverlayPosition pos) override
No-op — labels are always drawn at fixed cardinal edges.
void SetTextColor (const QColor &color)
void SetFontSize (int pt)
void SetLongLabels (bool longLabels)
Toggle between short (L/R/A/P/S/I) and long (Left/Right/Anterior/Posterior/Superior/Inferior) label mode.
void SetSliceOrientation (SliceOrientation orientation)
void SetViewportRect (double xMin, double yMin, double xMax, double yMax)
Restrict painting to a normalised sub-rectangle of the host widget.
Public Member Functions inherited from overlays::IOverlay
virtual ~IOverlay ()=default
virtual bool IsEnabled () const
OverlayPosition GetPosition () const
Static Public Attributes
static constexpr SliceOrientation kSliceOrientations [3]
Protected Member Functions
bool eventFilter (QObject *watched, QEvent *event) override
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Protected Attributes inherited from overlays::IOverlay
OverlayPosition m_position {OverlayPosition::TopLeft}
bool m_enabled {true}
Detailed Description
Anatomical orientation label overlay rendered as a child widget on top of a QVTKOpenGLNativeWidget.
Draws four labels at the cardinal edges of the viewport (left, right, top, bottom). Labels are derived from orientation:
Axial (XY): L/Left · R/Right · A/Anterior · P/Posterior
Coronal (XZ): L/Left · R/Right · S/Superior · I/Inferior
Sagittal (YZ): A/Anterior · P/Posterior · S/Superior · I/Inferior
Use SetLongLabels(true) to switch from abbreviated (L, R, …) to full anatomical names (Left, Right, …).
In shared-viewport mode (one widget, multiple renderers side-by-side) call SetViewportFraction() to restrict painting to a horizontal sub-region.
Rendering is a lightweight Qt paint operation — no VTK pipeline involvement. The overlay tracks host resize events via an event filter so it always fills the host widget.
Definition at line 36 of file OrientationMarkerOverlay.hpp.
Member Enumeration Documentation
SliceOrientation
enum class overlays::OrientationMarkerOverlay::SliceOrientation strong
Enumerator
Axial
Coronal
Sagittal
Definition at line 40 of file OrientationMarkerOverlay.hpp.
Constructor & Destructor Documentation
OrientationMarkerOverlay()
overlays::OrientationMarkerOverlay::OrientationMarkerOverlay (QVTKOpenGLNativeWidget * host, SliceOrientation orientation = SliceOrientation::Axial) explicit
Definition at line 31 of file OrientationMarkerOverlay.cpp.
~OrientationMarkerOverlay()
overlays::OrientationMarkerOverlay::~OrientationMarkerOverlay () override
Definition at line 46 of file OrientationMarkerOverlay.cpp.
Member Function Documentation
eventFilter()
bool overlays::OrientationMarkerOverlay::eventFilter (QObject * watched, QEvent * event) override protected
Definition at line 108 of file OrientationMarkerOverlay.cpp.
paintEvent()
void overlays::OrientationMarkerOverlay::paintEvent (QPaintEvent * event) override protected
Definition at line 116 of file OrientationMarkerOverlay.cpp.
References overlays::IOverlay::m_enabled.
SetEnabled()
void overlays::OrientationMarkerOverlay::SetEnabled (bool enabled) override virtual
Enable or disable the overlay.
Implements overlays::IOverlay.
Definition at line 53 of file OrientationMarkerOverlay.cpp.
References overlays::IOverlay::m_enabled.
Referenced by ui::ControllerPanelOrientationMarkerItem::AddOverlay().
SetFontSize()
void overlays::OrientationMarkerOverlay::SetFontSize (int pt)
Definition at line 71 of file OrientationMarkerOverlay.cpp.
Referenced by ui::ControllerPanelOrientationMarkerItem::AddOverlay().
SetLongLabels()
void overlays::OrientationMarkerOverlay::SetLongLabels (bool longLabels)
Toggle between short (L/R/A/P/S/I) and long (Left/Right/Anterior/Posterior/Superior/Inferior) label mode.
Definition at line 79 of file OrientationMarkerOverlay.cpp.
Referenced by ui::ControllerPanelOrientationMarkerItem::AddOverlay().
SetPosition()
void overlays::OrientationMarkerOverlay::SetPosition (OverlayPosition pos) override virtual
No-op — labels are always drawn at fixed cardinal edges.
Implements overlays::IOverlay.
Definition at line 60 of file OrientationMarkerOverlay.cpp.
SetSliceOrientation()
void overlays::OrientationMarkerOverlay::SetSliceOrientation (SliceOrientation orientation)
Definition at line 88 of file OrientationMarkerOverlay.cpp.
SetTextColor()
void overlays::OrientationMarkerOverlay::SetTextColor (const QColor & color)
Definition at line 64 of file OrientationMarkerOverlay.cpp.
Referenced by ui::ControllerPanelOrientationMarkerItem::AddOverlay().
SetViewportRect()
void overlays::OrientationMarkerOverlay::SetViewportRect (double xMin, double yMin, double xMax, double yMax)
Restrict painting to a normalised sub-rectangle of the host widget.
Coordinates are in Qt space (top-left origin, y grows downward), all in [0, 1]. Default (0, 0, 1, 1) covers the full widget.
Definition at line 95 of file OrientationMarkerOverlay.cpp.
Referenced by adapters::ApplyRect().
Member Data Documentation
kSliceOrientations
constexpr OrientationMarkerOverlay::SliceOrientation overlays::OrientationMarkerOverlay::kSliceOrientations static constexpr
Initial value:
= {
        SliceOrientation::Axial,
        SliceOrientation::Coronal,
        SliceOrientation::Sagittal,
    }
Definition at line 47 of file OrientationMarkerOverlay.hpp.
The documentation for this class was generated from the following files:
src/overlays/include/overlays/OrientationMarkerOverlay.hpp
src/overlays/src/OrientationMarkerOverlay.cpp