XQMprViewer: ui::ControllerPanelOrientationMarkerItem Class Reference
ui::ControllerPanelOrientationMarkerItem Class Reference
Control panel item for anatomical orientation marker overlay.
#include <ControllerPanelOrientationMarkerItem.hpp>
Public Member Functions
ControllerPanelOrientationMarkerItem (QWidget *parent=nullptr)
~ControllerPanelOrientationMarkerItem () override
void AddOverlay (overlays::OrientationMarkerOverlay *overlay)
Attach an overlay to be controlled by this panel.
void ClearOverlays ()
Detach all overlays.
signals::void OrientationMarkerEnableChanged (bool enabled)
void OrientationMarkerLongLabelsChanged (bool longLabels)
void OrientationMarkerColorChanged (const QColor &color)
void OrientationMarkerFontSizeChanged (int fontSize)
Detailed Description
Control panel item for anatomical orientation marker overlay.
Manages one or more OrientationMarkerOverlay instances simultaneously. All attached overlays are kept in sync with the panel settings.
Controls:
Enable / disable toggle (checkbox)
Long labels toggle: switches between L/R/A/P/S/I and full anatomical names
Font size (spin box, pt)
Label color (color picker button)
Definition at line 27 of file ControllerPanelOrientationMarkerItem.hpp.
Constructor & Destructor Documentation
ControllerPanelOrientationMarkerItem()
ui::ControllerPanelOrientationMarkerItem::ControllerPanelOrientationMarkerItem (QWidget * parent = nullptr) explicit
Definition at line 13 of file ControllerPanelOrientationMarkerItem.cpp.
~ControllerPanelOrientationMarkerItem()
ui::ControllerPanelOrientationMarkerItem::~ControllerPanelOrientationMarkerItem () override default
Member Function Documentation
AddOverlay()
void ui::ControllerPanelOrientationMarkerItem::AddOverlay (overlays::OrientationMarkerOverlay * overlay)
Attach an overlay to be controlled by this panel.
Definition at line 20 of file ControllerPanelOrientationMarkerItem.cpp.
References overlays::OrientationMarkerOverlay::SetEnabled(), overlays::OrientationMarkerOverlay::SetFontSize(), overlays::OrientationMarkerOverlay::SetLongLabels(), and overlays::OrientationMarkerOverlay::SetTextColor().
ClearOverlays()
void ui::ControllerPanelOrientationMarkerItem::ClearOverlays ()
Detach all overlays.
Definition at line 30 of file ControllerPanelOrientationMarkerItem.cpp.
OrientationMarkerColorChanged()
void ui::ControllerPanelOrientationMarkerItem::OrientationMarkerColorChanged (const QColor & color)
OrientationMarkerEnableChanged()
signals::void ui::ControllerPanelOrientationMarkerItem::OrientationMarkerEnableChanged (bool enabled)
OrientationMarkerFontSizeChanged()
void ui::ControllerPanelOrientationMarkerItem::OrientationMarkerFontSizeChanged (int fontSize)
OrientationMarkerLongLabelsChanged()
void ui::ControllerPanelOrientationMarkerItem::OrientationMarkerLongLabelsChanged (bool longLabels)
The documentation for this class was generated from the following files:
src/ui/include/ui/ControllerPanelOrientationMarkerItem.hpp
src/ui/src/ControllerPanelOrientationMarkerItem.cpp