XQMprViewer: overlays::FPSOverlay Class Reference
overlays::FPSOverlay Class Reference
Qt-native FPS overlay that lives as a child widget on top of a QVTKOpenGLNativeWidget and tracks real OpenGL frame swap time.
#include <FPSOverlay.hpp>
Public Member Functions
FPSOverlay (QVTKOpenGLNativeWidget *host)
~FPSOverlay () override=default
void SetEnabled (bool enabled) override
Enable or disable the overlay.
void SetTextColor (const QColor &color)
void SetFontSize (int pt)
void SetAveragingWindow (int seconds)
Set the sliding-window duration for FPS/frame-time averaging (1–60 s).
void SetPosition (OverlayPosition pos) override
Set position for the visible overlay.
void SetMargin (int px)
Public Member Functions inherited from overlays::IOverlay
virtual ~IOverlay ()=default
virtual bool IsEnabled () const
OverlayPosition GetPosition () const
Protected Member Functions
void resizeEvent (QResizeEvent *event) override
Additional Inherited Members
Protected Attributes inherited from overlays::IOverlay
OverlayPosition m_position {OverlayPosition::TopLeft}
bool m_enabled {true}
Detailed Description
Qt-native FPS overlay that lives as a child widget on top of a QVTKOpenGLNativeWidget and tracks real OpenGL frame swap time.
Timing is driven by the host widget's frameSwapped() signal, which fires after each OpenGL buffer swap — this captures the full GPU+CPU round-trip per frame rather than VTK's internal render timer.
FPS and frame-time values are averaged over a configurable sliding window (default 1 s, adjustable via SetAveragingWindow()) to produce a stable readable display rather than per-frame noise.
Configuration (position, margin, text color, font size, averaging window) can be changed at any time and takes effect on the next frame.
Definition at line 31 of file FPSOverlay.hpp.
Constructor & Destructor Documentation
FPSOverlay()
overlays::FPSOverlay::FPSOverlay (QVTKOpenGLNativeWidget * host) explicit
Definition at line 12 of file FPSOverlay.cpp.
~FPSOverlay()
overlays::FPSOverlay::~FPSOverlay () override default
Member Function Documentation
resizeEvent()
void overlays::FPSOverlay::resizeEvent (QResizeEvent * event) override protected
Definition at line 69 of file FPSOverlay.cpp.
SetAveragingWindow()
void overlays::FPSOverlay::SetAveragingWindow (int seconds)
Set the sliding-window duration for FPS/frame-time averaging (1–60 s).
Definition at line 76 of file FPSOverlay.cpp.
Referenced by ui::ControllerPanelFPSOverlayItem::AddOverlay().
SetEnabled()
void overlays::FPSOverlay::SetEnabled (bool enabled) override virtual
Enable or disable the overlay.
Implements overlays::IOverlay.
Definition at line 40 of file FPSOverlay.cpp.
References overlays::IOverlay::m_enabled.
Referenced by ui::ControllerPanelFPSOverlayItem::AddOverlay().
SetFontSize()
void overlays::FPSOverlay::SetFontSize (int pt)
Definition at line 51 of file FPSOverlay.cpp.
Referenced by ui::ControllerPanelFPSOverlayItem::AddOverlay().
SetMargin()
void overlays::FPSOverlay::SetMargin (int px)
Definition at line 64 of file FPSOverlay.cpp.
Referenced by ui::ControllerPanelFPSOverlayItem::AddOverlay().
SetPosition()
void overlays::FPSOverlay::SetPosition (OverlayPosition pos) override virtual
Set position for the visible overlay.
Implements overlays::IOverlay.
Definition at line 59 of file FPSOverlay.cpp.
References overlays::IOverlay::m_position.
Referenced by ui::ControllerPanelFPSOverlayItem::AddOverlay().
SetTextColor()
void overlays::FPSOverlay::SetTextColor (const QColor & color)
Definition at line 45 of file FPSOverlay.cpp.
Referenced by ui::ControllerPanelFPSOverlayItem::AddOverlay().
The documentation for this class was generated from the following files:
src/overlays/include/overlays/FPSOverlay.hpp
src/overlays/src/FPSOverlay.cpp