XQMprViewer: overlays::CornerAnnotationOverlay Class Reference
overlays::CornerAnnotationOverlay Class Reference
Slice-metadata annotation overlay rendered as a child widget on a QVTKOpenGLNativeWidget.
#include <CornerAnnotationOverlay.hpp>
Public Member Functions
CornerAnnotationOverlay (QVTKOpenGLNativeWidget *host, const QString &viewName=QString())
~CornerAnnotationOverlay () override
void SetEnabled (bool enabled) override
Enable or disable the overlay.
void SetPosition (OverlayPosition pos) override
Set position for the visible overlay.
void SetViewer (vtkResliceImageViewer *viewer)
Attach the viewer from which slice/window-level data is read. Non-owning.
void SetViewName (const QString &name)
Override the view name line. Defaults to the constructor argument.
void SetTextColor (const QColor &color)
void SetFontSize (int pt)
void SetMargin (int px)
void SetShowSliceInfo (bool show)
void SetShowWindowLevel (bool show)
void SetShowSpacing (bool show)
void SetShowViewName (bool show)
void SetViewportRect (double xMin, double yMin, double xMax, double yMax)
Restrict painting to a normalised sub-rectangle of the host widget.
Public Member Functions inherited from overlays::IOverlay
virtual ~IOverlay ()=default
virtual bool IsEnabled () const
OverlayPosition GetPosition () const
Protected Member Functions
bool eventFilter (QObject *watched, QEvent *event) override
void paintEvent (QPaintEvent *event) override
void resizeEvent (QResizeEvent *event) override
Additional Inherited Members
Protected Attributes inherited from overlays::IOverlay
OverlayPosition m_position {OverlayPosition::TopLeft}
bool m_enabled {true}
Detailed Description
Slice-metadata annotation overlay rendered as a child widget on a QVTKOpenGLNativeWidget.
Displays enabled metadata lines (slice index/count, window/level, spacing, view name) stacked vertically inside a single text block positioned at any corner or edge via SetPosition() — identical placement mechanics to FPSOverlay.
Data is read from the attached vtkResliceImageViewer on every frameSwapped() event, so values update automatically during interaction.
In shared-viewport mode (one widget, multiple renderers) call SetViewportFraction() to restrict painting to a horizontal sub-region.
Definition at line 31 of file CornerAnnotationOverlay.hpp.
Constructor & Destructor Documentation
CornerAnnotationOverlay()
overlays::CornerAnnotationOverlay::CornerAnnotationOverlay (QVTKOpenGLNativeWidget * host, const QString & viewName = QString()) explicit
Definition at line 17 of file CornerAnnotationOverlay.cpp.
References overlays::BottomRight, and overlays::IOverlay::m_position.
~CornerAnnotationOverlay()
overlays::CornerAnnotationOverlay::~CornerAnnotationOverlay () override
Definition at line 36 of file CornerAnnotationOverlay.cpp.
Member Function Documentation
eventFilter()
bool overlays::CornerAnnotationOverlay::eventFilter (QObject * watched, QEvent * event) override protected
Definition at line 138 of file CornerAnnotationOverlay.cpp.
paintEvent()
void overlays::CornerAnnotationOverlay::paintEvent (QPaintEvent * event) override protected
Definition at line 160 of file CornerAnnotationOverlay.cpp.
References overlays::BottomCenter, overlays::BottomLeft, overlays::BottomRight, overlays::IOverlay::m_enabled, overlays::IOverlay::m_position, overlays::TopCenter, overlays::TopLeft, and overlays::TopRight.
resizeEvent()
void overlays::CornerAnnotationOverlay::resizeEvent (QResizeEvent * event) override protected
Definition at line 146 of file CornerAnnotationOverlay.cpp.
SetEnabled()
void overlays::CornerAnnotationOverlay::SetEnabled (bool enabled) override virtual
Enable or disable the overlay.
Implements overlays::IOverlay.
Definition at line 43 of file CornerAnnotationOverlay.cpp.
References overlays::IOverlay::m_enabled.
Referenced by ui::ControllerPanelCornerAnnotationItem::AddOverlay().
SetFontSize()
void overlays::CornerAnnotationOverlay::SetFontSize (int pt)
Definition at line 78 of file CornerAnnotationOverlay.cpp.
Referenced by ui::ControllerPanelCornerAnnotationItem::AddOverlay().
SetMargin()
void overlays::CornerAnnotationOverlay::SetMargin (int px)
Definition at line 86 of file CornerAnnotationOverlay.cpp.
Referenced by ui::ControllerPanelCornerAnnotationItem::AddOverlay().
SetPosition()
void overlays::CornerAnnotationOverlay::SetPosition (OverlayPosition pos) override virtual
Set position for the visible overlay.
Implements overlays::IOverlay.
Definition at line 50 of file CornerAnnotationOverlay.cpp.
References overlays::IOverlay::m_position.
Referenced by ui::ControllerPanelCornerAnnotationItem::AddOverlay().
SetShowSliceInfo()
void overlays::CornerAnnotationOverlay::SetShowSliceInfo (bool show)
Definition at line 95 of file CornerAnnotationOverlay.cpp.
Referenced by ui::ControllerPanelCornerAnnotationItem::AddOverlay().
SetShowSpacing()
void overlays::CornerAnnotationOverlay::SetShowSpacing (bool show)
Definition at line 109 of file CornerAnnotationOverlay.cpp.
Referenced by ui::ControllerPanelCornerAnnotationItem::AddOverlay().
SetShowViewName()
void overlays::CornerAnnotationOverlay::SetShowViewName (bool show)
Definition at line 116 of file CornerAnnotationOverlay.cpp.
Referenced by ui::ControllerPanelCornerAnnotationItem::AddOverlay().
SetShowWindowLevel()
void overlays::CornerAnnotationOverlay::SetShowWindowLevel (bool show)
Definition at line 102 of file CornerAnnotationOverlay.cpp.
Referenced by ui::ControllerPanelCornerAnnotationItem::AddOverlay().
SetTextColor()
void overlays::CornerAnnotationOverlay::SetTextColor (const QColor & color)
Definition at line 71 of file CornerAnnotationOverlay.cpp.
Referenced by ui::ControllerPanelCornerAnnotationItem::AddOverlay().
SetViewer()
void overlays::CornerAnnotationOverlay::SetViewer (vtkResliceImageViewer * viewer)
Attach the viewer from which slice/window-level data is read. Non-owning.
Definition at line 57 of file CornerAnnotationOverlay.cpp.
SetViewName()
void overlays::CornerAnnotationOverlay::SetViewName (const QString & name)
Override the view name line. Defaults to the constructor argument.
Definition at line 62 of file CornerAnnotationOverlay.cpp.
SetViewportRect()
void overlays::CornerAnnotationOverlay::SetViewportRect (double xMin, double yMin, double xMax, double yMax)
Restrict painting to a normalised sub-rectangle of the host widget.
Coordinates are in Qt space (top-left origin, y grows downward), all in [0, 1]. Default (0, 0, 1, 1) covers the full widget.
Definition at line 125 of file CornerAnnotationOverlay.cpp.
Referenced by adapters::ApplyRect().
The documentation for this class was generated from the following files:
src/overlays/include/overlays/CornerAnnotationOverlay.hpp
src/overlays/src/CornerAnnotationOverlay.cpp