XQMprViewer: adapters::OverlayLayoutAdapter Class Reference
adapters::OverlayLayoutAdapter Class Reference
Bridges the layout system and the overlay system for one IView.
#include <OverlayLayoutAdapter.hpp>
Public Member Functions
OverlayLayoutAdapter (bool sharedViewport)
void AddOrientationMarkerOverlay (overlays::OrientationMarkerOverlay *ov)
Register overlays in planeIndex order (0=Axial, 1=Coronal, 2=Sagittal).
void AddCornerAnnotationOverlay (overlays::CornerAnnotationOverlay *ov)
void AddFPSOverlay (overlays::FPSOverlay *ov)
void Sync (const ui::ViewportLayoutDefinition &def)
Synchronise all registered overlays to the given layout definition.
void SetOrientationMarkerUserEnabled (int planeIndex, bool enabled)
Notify the adapter that the user has toggled orientation marker enable state for plane planeIndex.
void SetCornerAnnotationUserEnabled (int planeIndex, bool enabled)
void SetAllOrientationMarkersUserEnabled (bool enabled)
Apply user-enable for ALL planes at once (e.g., global checkbox).
void SetAllCornerAnnotationsUserEnabled (bool enabled)
Detailed Description
Bridges the layout system and the overlay system for one IView.
Manages the interplay between two independent visibility axes:
Axis A — User toggle (enabled/disabled via ControllerPanel). Axis B — Layout visibility (is this plane's pane present in the active layout?).
An overlay is shown only when BOTH axes are true.
Usage:
Construct with sharedViewport=true for ViewportView (one widget), false for MultiWindowView (one widget per plane).
Register overlays with AddXxxOverlay(). Order = planeIndex (0/1/2).
Call Sync() whenever the layout changes.
Call NotifyUserEnabled<T>(i, bool) when the user toggles an overlay type so the adapter can recompute visibility correctly.
Definition at line 35 of file OverlayLayoutAdapter.hpp.
Constructor & Destructor Documentation
OverlayLayoutAdapter()
adapters::OverlayLayoutAdapter::OverlayLayoutAdapter (bool sharedViewport) explicit
Definition at line 9 of file OverlayLayoutAdapter.cpp.
Member Function Documentation
AddCornerAnnotationOverlay()
void adapters::OverlayLayoutAdapter::AddCornerAnnotationOverlay (overlays::CornerAnnotationOverlay * ov)
Definition at line 19 of file OverlayLayoutAdapter.cpp.
AddFPSOverlay()
void adapters::OverlayLayoutAdapter::AddFPSOverlay (overlays::FPSOverlay * ov)
Definition at line 24 of file OverlayLayoutAdapter.cpp.
AddOrientationMarkerOverlay()
void adapters::OverlayLayoutAdapter::AddOrientationMarkerOverlay (overlays::OrientationMarkerOverlay * ov)
Register overlays in planeIndex order (0=Axial, 1=Coronal, 2=Sagittal).
Ownership is NOT transferred; the caller (IView) owns the overlays. Each Add call appends one entry; call exactly once per plane per type.
Definition at line 14 of file OverlayLayoutAdapter.cpp.
SetAllCornerAnnotationsUserEnabled()
void adapters::OverlayLayoutAdapter::SetAllCornerAnnotationsUserEnabled (bool enabled)
Definition at line 85 of file OverlayLayoutAdapter.cpp.
References SetCornerAnnotationUserEnabled().
SetAllOrientationMarkersUserEnabled()
void adapters::OverlayLayoutAdapter::SetAllOrientationMarkersUserEnabled (bool enabled)
Apply user-enable for ALL planes at once (e.g., global checkbox).
Definition at line 80 of file OverlayLayoutAdapter.cpp.
References SetOrientationMarkerUserEnabled().
SetCornerAnnotationUserEnabled()
void adapters::OverlayLayoutAdapter::SetCornerAnnotationUserEnabled (int planeIndex, bool enabled)
Definition at line 70 of file OverlayLayoutAdapter.cpp.
Referenced by SetAllCornerAnnotationsUserEnabled().
SetOrientationMarkerUserEnabled()
void adapters::OverlayLayoutAdapter::SetOrientationMarkerUserEnabled (int planeIndex, bool enabled)
Notify the adapter that the user has toggled orientation marker enable state for plane planeIndex.
The adapter recomputes the widget visibility as (userEnabled AND layoutVisible).
Definition at line 60 of file OverlayLayoutAdapter.cpp.
Referenced by SetAllOrientationMarkersUserEnabled().
Sync()
void adapters::OverlayLayoutAdapter::Sync (const ui::ViewportLayoutDefinition & def)
Synchronise all registered overlays to the given layout definition.
Updates viewport fractions (shared-viewport mode) and widget visibility for all registered overlays. User-enable state is preserved.
Definition at line 29 of file OverlayLayoutAdapter.cpp.
References ui::ViewportLayoutDefinition::panes.
The documentation for this class was generated from the following files:
src/adapters/include/adapters/OverlayLayoutAdapter.hpp
src/adapters/src/OverlayLayoutAdapter.cpp